### ISSUE TITLE
Reload templates on save with jar packaging

### ISSUE THREAD

**Issue by nek4life** [jtwig/jtwig-spring-boot-starter#10]
Is there a way to get the templates to reload on save without recompiling? I've been trying to set this up based on an example when I just noticed this package. I see in the config that cache is set to true. I've tried setting it to false, then it works when I recompile, but I was hoping there was a way to update the templates when the file is saved.

**Comment by lyncodev** [comment]
At the moment there is no such capability.

**Comment by nek4life** [comment]
Ok I was trying to get it to work and thought I'd ask before I kept going. I could reload the templates with cache set to false and then recompiling. However, having hot reload would be great.

**Comment by lyncodev** [comment]
Yes, we just need to have an implementation for the TemplateCache interface
https://github.com/jtwig/jtwig-core/blob/master/src/main/java/org/jtwig/parser/cache/TemplateCache.java
to
be able to evict an item out of date (according to the FS). Seems like a
quick win.

**Comment by lyncodev** [comment]
I'm still writing the documentation on advanced Jtwig configuration (version 5). Some documentation can be found here https://www.gitbook.com/book/jtwig/jtwig-reference-manual/details.

**Comment by nek4life** [comment]
Thanks for the links! This is super helpful. I've been interested in using spring-boot for application development, but every time I get to the templates I haven't been able to find a decent template language that has block inheritance that doesn't use some xml library like tiles. I usually build web apps in Python using Jinja2 so jTwig looks perfect and I'm super interested in giving it a go. Having hot reloading would definitely help me change my mind on the spring-boot decision for web sites. I've used it for building apis before, but that doesn't require templates.

Thanks again!

**Comment by lyncodev** [comment]
Check this proposal: https://github.com/jtwig/jtwig-hot-reloading-extension. Note that you need to update your spring boot starter version to 5.15
